keyboard: nanosic_driver: Fix an implicit-int error
nano_macro.h:318:32: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
__attribute__((unused)) static xiaomi_keyboard_init(
                       ~~~~~~ ^
int
1 error generated.